import { Shield, Headset, Stethoscope, Target, Radio, Crosshair, Car, Briefcase } from 'lucide-react';

export const companyData = {
  name: "AEGIS & CO.",
  tagline: "The Pinnacle of Executive Protection",
};

export const teamData = [
  {
    name: "앨런 그레이",
    engName: "Alan Gray",
    role: "팀장",
    age: 35,
    bloodType: "A",
    mbti: "INTJ",
    enneagram: "5w6",
    height: "188cm",
    callsign: "Viper Actual",
    keywords: ["다정함", "여유로움", "안정형 리더", "젤리 매니아", "완벽한 평정심"],
    icon: <Target className="w-5 h-5" />,
    imageUrl: "https://i.postimg.cc/GmhfrDhp/aelleon.png",
    color: { main: '#a78bfa', dark: '#4c1d95', bg: '#4c1d9540' }
  },
  {
    name: "재커리 콜",
    engName: "Zachary Cole",
    role: "부팀장 / 관제",
    age: 37,
    bloodType: "O",
    mbti: "INTP",
    enneagram: "5w6",
    height: "186cm",
    callsign: "Command",
    keywords: ["만성피로", "무덤덤", "효율 중시", "사담 철벽"],
    icon: <Headset className="w-5 h-5" />,
    imageUrl: "https://i.postimg.cc/hty5GGfQ/jaekeoli.png",
    color: { main: '#818cf8', dark: '#312e81', bg: '#312e8140' }
  },
  {
    name: "다니엘 워커",
    engName: "Daniel Walker",
    role: "정보분석",
    age: 30,
    bloodType: "AB",
    mbti: "INFJ",
    enneagram: "1w9",
    height: "179cm",
    callsign: "Signal",
    keywords: ["순둥이", "정중한 거리두기", "다정함", "강아지상", "완벽한 서포트"],
    icon: <Radio className="w-5 h-5" />,
    imageUrl: "https://i.postimg.cc/wTkrS2zW/daniel.png",
    color: { main: '#60a5fa', dark: '#1e3a8a', bg: '#1e3a8a40' }
  },
  {
    name: "에이든 폭스",
    engName: "Aiden Fox",
    role: "드라이버",
    age: 32,
    bloodType: "O",
    mbti: "ENFP",
    enneagram: "6w7",
    height: "185cm",
    callsign: "Motor",
    keywords: ["허당", "분위기 메이커", "운전대 잡으면 돌변"],
    icon: <Car className="w-5 h-5" />,
    imageUrl: "https://i.postimg.cc/DwyNFGyf/eideun.png",
    color: { main: '#fb7185', dark: '#881337', bg: '#88133740' }
  },
  {
    name: "루카스 마틴",
    engName: "Lucas Martin",
    role: "지정사수",
    age: 30,
    bloodType: "B",
    mbti: "ESFP",
    enneagram: "7w6",
    height: "188cm",
    callsign: "Overwatch",
    keywords: ["나른함", "귀차니즘", "본업 천재", "깔끔한 멘탈", "냉철함"],
    icon: <Crosshair className="w-5 h-5" />,
    imageUrl: "https://i.postimg.cc/YCqPkFqp/lukaseu.png",
    color: { main: '#38bdf8', dark: '#0c4a6e', bg: '#0c4a6e40' }
  },
  {
    name: "테디 크루거",
    engName: "Teddy Kruger",
    role: "의무관",
    age: 34,
    bloodType: "AB",
    mbti: "ENTP",
    enneagram: "3w4",
    height: "184cm",
    callsign: "Medic",
    keywords: ["과로", "예민함", "츤데레", "가식쟁이"],
    icon: <Stethoscope className="w-5 h-5" />,
    imageUrl: "https://i.postimg.cc/LsJ0gM1W/tedi.png",
    color: { main: '#e879f9', dark: '#701a75', bg: '#701a7540' }
  },
  {
    name: "딘 테일러",
    engName: "Dean Taylor",
    role: "포인트맨",
    age: 33,
    bloodType: "A",
    mbti: "ESFJ",
    enneagram: "2w3",
    height: "193cm",
    callsign: "Point",
    keywords: ["긍정왕", "대형견", "잔망꾸러기", "든든함"],
    icon: <Shield className="w-5 h-5" />,
    imageUrl: "https://i.postimg.cc/vZHKMnHY/din.png",
    color: { main: '#c084fc', dark: '#581c87', bg: '#581c8740' }
  },
  {
    name: "조엘 심슨",
    engName: "Joel Simpson",
    role: "기동타격",
    age: 31,
    bloodType: "B",
    mbti: "ESTP",
    enneagram: "7w8",
    height: "187cm",
    callsign: "Flank",
    keywords: ["대담함", "능청스러움", "도파민 중독", "지능형 또라이"],
    icon: <Target className="w-5 h-5" />,
    imageUrl: "https://i.postimg.cc/cJv5tNn9/jo-el.png",
    color: { main: '#f87171', dark: '#7f1d1d', bg: '#7f1d1d40' }
  },
  {
    name: "제시 힉스",
    engName: "Jesse Hicks",
    role: "대외협상",
    age: 32,
    bloodType: "O",
    mbti: "ENTJ",
    enneagram: "8w9",
    height: "186cm",
    callsign: "Scout",
    keywords: ["능구렁이", "팩폭러", "여유로움", "닉 와일드"],
    icon: <Briefcase className="w-5 h-5" />,
    imageUrl: "https://i.postimg.cc/BvjwPGK2/jesi.png",
    color: { main: '#f472b6', dark: '#831843', bg: '#83184340' }
  }
];
